# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-31 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cmdTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('ownerid', models.IntegerField(default=1)),
                ('cmd', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('runlevel', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='runLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('level', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='winterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(db_index=True, max_length=32)),
                ('passwd', models.CharField(max_length=32)),
                ('runLevel', models.IntegerField(blank=True, db_index=True)),
            ],
        ),
    ]
